name: Detect Public Copies of ALPHA

on:
  schedule:
    - cron: '0 0 * * *'   # Roz midnight UTC (00:00 UTC pe chalega)
  workflow_dispatch:       # Manual run option

jobs:
  search-token:
    runs-on: ubuntu-latest
    steps:
      - name: Search for unique token on GitHub
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tokenToFind = "ALPHA-SEC-2025-ABJ-UNQ-9173X"; // 👈 Tumhara unique token
            const q = `${tokenToFind} in:file`;
            const results = await github.rest.search.code({
              q,
              per_page: 10
            });

            if (results.data.total_count > 0) {
              const places = results.data.items.map(i => `${i.repository.full_name} -> ${i.html_url}`).join('\n');
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `🚨 Possible Copy Detected for ALPHA (${tokenToFind})`,
                body: `The unique token **${tokenToFind}** was found in:\n\n${places}\n\nPlease review.`
              });
              console.log(`⚠️ Copies detected:\n${places}`);
            } else {
              console.log("✅ No matches found.");
            }
